name: ci - automation exercise

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # prevent a hung job from running forever
    timeout-minutes: 30

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Use Node.js 18 (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Restore Cypress binary cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-binary-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-binary-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests (action)
        uses: cypress-io/github-action@v6
        with:
          # run the standard CLI but disable video to speed up runs
          command: npx cypress run --config video=false

      - name: Upload Cypress screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload test reports (if present)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: cypress/reports
          if-no-files-found: ignore
